version: "3"

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db

  api:
    build: .
    environment:
      - DEBUG=True
      - MONGO_HOST=localhost
      - MONGO_DB=forexInternational
      - MAX_WORKERS=1
    network_mode: "host"
